/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AssertionPrevalence
 */


public class AssertionPrevalence {
  @SerializedName("studyId")
  private String studyId = null;

  @SerializedName("percent")
  private Float percent = null;

  @SerializedName("samples")
  private Integer samples = null;

  @SerializedName("count")
  private Integer count = null;

  public AssertionPrevalence studyId(String studyId) {
    this.studyId = studyId;
    return this;
  }

   /**
   * Get studyId
   * @return studyId
  **/
  @Schema(required = true, description = "")
  public String getStudyId() {
    return studyId;
  }

  public void setStudyId(String studyId) {
    this.studyId = studyId;
  }

  public AssertionPrevalence percent(Float percent) {
    this.percent = percent;
    return this;
  }

   /**
   * Get percent
   * @return percent
  **/
  @Schema(required = true, description = "")
  public Float getPercent() {
    return percent;
  }

  public void setPercent(Float percent) {
    this.percent = percent;
  }

  public AssertionPrevalence samples(Integer samples) {
    this.samples = samples;
    return this;
  }

   /**
   * Get samples
   * @return samples
  **/
  @Schema(required = true, description = "")
  public Integer getSamples() {
    return samples;
  }

  public void setSamples(Integer samples) {
    this.samples = samples;
  }

  public AssertionPrevalence count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @Schema(required = true, description = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssertionPrevalence assertionPrevalence = (AssertionPrevalence) o;
    return Objects.equals(this.studyId, assertionPrevalence.studyId) &&
        Objects.equals(this.percent, assertionPrevalence.percent) &&
        Objects.equals(this.samples, assertionPrevalence.samples) &&
        Objects.equals(this.count, assertionPrevalence.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(studyId, percent, samples, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssertionPrevalence {\n");
    
    sb.append("    studyId: ").append(toIndentedString(studyId)).append("\n");
    sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
    sb.append("    samples: ").append(toIndentedString(samples)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
