/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AssertionClassifications
 */


public class AssertionClassifications {
  @SerializedName("name")
  private String name = null;

  @SerializedName("classification")
  private String classification = null;

  @SerializedName("classificationOverride")
  private String classificationOverride = null;

  public AssertionClassifications name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AssertionClassifications classification(String classification) {
    this.classification = classification;
    return this;
  }

   /**
   * Get classification
   * @return classification
  **/
  @Schema(required = true, description = "")
  public String getClassification() {
    return classification;
  }

  public void setClassification(String classification) {
    this.classification = classification;
  }

  public AssertionClassifications classificationOverride(String classificationOverride) {
    this.classificationOverride = classificationOverride;
    return this;
  }

   /**
   * Get classificationOverride
   * @return classificationOverride
  **/
  @Schema(description = "")
  public String getClassificationOverride() {
    return classificationOverride;
  }

  public void setClassificationOverride(String classificationOverride) {
    this.classificationOverride = classificationOverride;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssertionClassifications assertionClassifications = (AssertionClassifications) o;
    return Objects.equals(this.name, assertionClassifications.name) &&
        Objects.equals(this.classification, assertionClassifications.classification) &&
        Objects.equals(this.classificationOverride, assertionClassifications.classificationOverride);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, classification, classificationOverride);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssertionClassifications {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    classificationOverride: ").append(toIndentedString(classificationOverride)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
