/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ClinicalTrialArmGroups
 */


public class ClinicalTrialArmGroups {
  @SerializedName("arm_group_label")
  private String armGroupLabel = null;

  @SerializedName("arm_group_type")
  private String armGroupType = null;

  @SerializedName("description")
  private String description = null;

  public ClinicalTrialArmGroups armGroupLabel(String armGroupLabel) {
    this.armGroupLabel = armGroupLabel;
    return this;
  }

   /**
   * Get armGroupLabel
   * @return armGroupLabel
  **/
  @Schema(required = true, description = "")
  public String getArmGroupLabel() {
    return armGroupLabel;
  }

  public void setArmGroupLabel(String armGroupLabel) {
    this.armGroupLabel = armGroupLabel;
  }

  public ClinicalTrialArmGroups armGroupType(String armGroupType) {
    this.armGroupType = armGroupType;
    return this;
  }

   /**
   * Get armGroupType
   * @return armGroupType
  **/
  @Schema(description = "")
  public String getArmGroupType() {
    return armGroupType;
  }

  public void setArmGroupType(String armGroupType) {
    this.armGroupType = armGroupType;
  }

  public ClinicalTrialArmGroups description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClinicalTrialArmGroups clinicalTrialArmGroups = (ClinicalTrialArmGroups) o;
    return Objects.equals(this.armGroupLabel, clinicalTrialArmGroups.armGroupLabel) &&
        Objects.equals(this.armGroupType, clinicalTrialArmGroups.armGroupType) &&
        Objects.equals(this.description, clinicalTrialArmGroups.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(armGroupLabel, armGroupType, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClinicalTrialArmGroups {\n");
    
    sb.append("    armGroupLabel: ").append(toIndentedString(armGroupLabel)).append("\n");
    sb.append("    armGroupType: ").append(toIndentedString(armGroupType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
