/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DrugBrands
 */


public class DrugBrands {
  @SerializedName("suppress")
  private Boolean suppress = null;

  @SerializedName("custom")
  private Boolean custom = null;

  @SerializedName("primary")
  private Boolean primary = null;

  @SerializedName("compositeKey")
  private String compositeKey = null;

  @SerializedName("indications")
  private String indications = null;

  @SerializedName("mechanism")
  private String mechanism = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("manufacturer")
  private String manufacturer = null;

  public DrugBrands suppress(Boolean suppress) {
    this.suppress = suppress;
    return this;
  }

   /**
   * Get suppress
   * @return suppress
  **/
  @Schema(description = "")
  public Boolean isSuppress() {
    return suppress;
  }

  public void setSuppress(Boolean suppress) {
    this.suppress = suppress;
  }

  public DrugBrands custom(Boolean custom) {
    this.custom = custom;
    return this;
  }

   /**
   * Get custom
   * @return custom
  **/
  @Schema(description = "")
  public Boolean isCustom() {
    return custom;
  }

  public void setCustom(Boolean custom) {
    this.custom = custom;
  }

  public DrugBrands primary(Boolean primary) {
    this.primary = primary;
    return this;
  }

   /**
   * Get primary
   * @return primary
  **/
  @Schema(description = "")
  public Boolean isPrimary() {
    return primary;
  }

  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }

  public DrugBrands compositeKey(String compositeKey) {
    this.compositeKey = compositeKey;
    return this;
  }

   /**
   * Get compositeKey
   * @return compositeKey
  **/
  @Schema(required = true, description = "")
  public String getCompositeKey() {
    return compositeKey;
  }

  public void setCompositeKey(String compositeKey) {
    this.compositeKey = compositeKey;
  }

  public DrugBrands indications(String indications) {
    this.indications = indications;
    return this;
  }

   /**
   * Get indications
   * @return indications
  **/
  @Schema(description = "")
  public String getIndications() {
    return indications;
  }

  public void setIndications(String indications) {
    this.indications = indications;
  }

  public DrugBrands mechanism(String mechanism) {
    this.mechanism = mechanism;
    return this;
  }

   /**
   * Get mechanism
   * @return mechanism
  **/
  @Schema(description = "")
  public String getMechanism() {
    return mechanism;
  }

  public void setMechanism(String mechanism) {
    this.mechanism = mechanism;
  }

  public DrugBrands name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DrugBrands manufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @Schema(required = true, description = "")
  public String getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrugBrands drugBrands = (DrugBrands) o;
    return Objects.equals(this.suppress, drugBrands.suppress) &&
        Objects.equals(this.custom, drugBrands.custom) &&
        Objects.equals(this.primary, drugBrands.primary) &&
        Objects.equals(this.compositeKey, drugBrands.compositeKey) &&
        Objects.equals(this.indications, drugBrands.indications) &&
        Objects.equals(this.mechanism, drugBrands.mechanism) &&
        Objects.equals(this.name, drugBrands.name) &&
        Objects.equals(this.manufacturer, drugBrands.manufacturer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suppress, custom, primary, compositeKey, indications, mechanism, name, manufacturer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrugBrands {\n");
    
    sb.append("    suppress: ").append(toIndentedString(suppress)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    compositeKey: ").append(toIndentedString(compositeKey)).append("\n");
    sb.append("    indications: ").append(toIndentedString(indications)).append("\n");
    sb.append("    mechanism: ").append(toIndentedString(mechanism)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
