/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DrugAvailability
 */


public class DrugAvailability {
  @SerializedName("region")
  private String region = null;

  @SerializedName("max_phase")
  private Integer maxPhase = null;

  @SerializedName("marketed_prescription")
  private Boolean marketedPrescription = null;

  @SerializedName("generic_available")
  private Boolean genericAvailable = null;

  @SerializedName("pre_market_cancelled")
  private Boolean preMarketCancelled = null;

  @SerializedName("post_market_cancelled")
  private Boolean postMarketCancelled = null;

  public DrugAvailability region(String region) {
    this.region = region;
    return this;
  }

   /**
   * A country or other jurisdiction.
   * @return region
  **/
  @Schema(required = true, description = "A country or other jurisdiction.")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public DrugAvailability maxPhase(Integer maxPhase) {
    this.maxPhase = maxPhase;
    return this;
  }

   /**
   * Maximum phase achieved during development.
   * @return maxPhase
  **/
  @Schema(required = true, description = "Maximum phase achieved during development.")
  public Integer getMaxPhase() {
    return maxPhase;
  }

  public void setMaxPhase(Integer maxPhase) {
    this.maxPhase = maxPhase;
  }

  public DrugAvailability marketedPrescription(Boolean marketedPrescription) {
    this.marketedPrescription = marketedPrescription;
    return this;
  }

   /**
   * Whether the drug has been marketed for prescription use.
   * @return marketedPrescription
  **/
  @Schema(required = true, description = "Whether the drug has been marketed for prescription use.")
  public Boolean isMarketedPrescription() {
    return marketedPrescription;
  }

  public void setMarketedPrescription(Boolean marketedPrescription) {
    this.marketedPrescription = marketedPrescription;
  }

  public DrugAvailability genericAvailable(Boolean genericAvailable) {
    this.genericAvailable = genericAvailable;
    return this;
  }

   /**
   * Whether the drug has been available as a generic
   * @return genericAvailable
  **/
  @Schema(required = true, description = "Whether the drug has been available as a generic")
  public Boolean isGenericAvailable() {
    return genericAvailable;
  }

  public void setGenericAvailable(Boolean genericAvailable) {
    this.genericAvailable = genericAvailable;
  }

  public DrugAvailability preMarketCancelled(Boolean preMarketCancelled) {
    this.preMarketCancelled = preMarketCancelled;
    return this;
  }

   /**
   * Whether the drug was cancelled before market-availability.
   * @return preMarketCancelled
  **/
  @Schema(required = true, description = "Whether the drug was cancelled before market-availability.")
  public Boolean isPreMarketCancelled() {
    return preMarketCancelled;
  }

  public void setPreMarketCancelled(Boolean preMarketCancelled) {
    this.preMarketCancelled = preMarketCancelled;
  }

  public DrugAvailability postMarketCancelled(Boolean postMarketCancelled) {
    this.postMarketCancelled = postMarketCancelled;
    return this;
  }

   /**
   * Whether the drug was cancelled after market-availability.
   * @return postMarketCancelled
  **/
  @Schema(required = true, description = "Whether the drug was cancelled after market-availability.")
  public Boolean isPostMarketCancelled() {
    return postMarketCancelled;
  }

  public void setPostMarketCancelled(Boolean postMarketCancelled) {
    this.postMarketCancelled = postMarketCancelled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrugAvailability drugAvailability = (DrugAvailability) o;
    return Objects.equals(this.region, drugAvailability.region) &&
        Objects.equals(this.maxPhase, drugAvailability.maxPhase) &&
        Objects.equals(this.marketedPrescription, drugAvailability.marketedPrescription) &&
        Objects.equals(this.genericAvailable, drugAvailability.genericAvailable) &&
        Objects.equals(this.preMarketCancelled, drugAvailability.preMarketCancelled) &&
        Objects.equals(this.postMarketCancelled, drugAvailability.postMarketCancelled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(region, maxPhase, marketedPrescription, genericAvailable, preMarketCancelled, postMarketCancelled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrugAvailability {\n");
    
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    maxPhase: ").append(toIndentedString(maxPhase)).append("\n");
    sb.append("    marketedPrescription: ").append(toIndentedString(marketedPrescription)).append("\n");
    sb.append("    genericAvailable: ").append(toIndentedString(genericAvailable)).append("\n");
    sb.append("    preMarketCancelled: ").append(toIndentedString(preMarketCancelled)).append("\n");
    sb.append("    postMarketCancelled: ").append(toIndentedString(postMarketCancelled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
