/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DrugAvailability;
import io.swagger.client.model.DrugBrands;
import io.swagger.client.model.DrugCompositeTags;
import io.swagger.client.model.DrugDosages;
import io.swagger.client.model.DrugDrugclass;
import io.swagger.client.model.DrugExternalIds;
import io.swagger.client.model.DrugParents;
import io.swagger.client.model.DrugPharmacology;
import io.swagger.client.model.DrugPrices;
import io.swagger.client.model.DrugSynonyms;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Drug
 */


public class Drug {
  @SerializedName("mboost")
  private Float mboost = null;

  /**
   * Gets or Sets analyzer
   */
  @JsonAdapter(AnalyzerEnum.Adapter.class)
  public enum AnalyzerEnum {
    DEFAULT("DEFAULT"),
    CASE_SENSITIVE("CASE_SENSITIVE");

    private String value;

    AnalyzerEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AnalyzerEnum fromValue(String text) {
      for (AnalyzerEnum b : AnalyzerEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AnalyzerEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalyzerEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalyzerEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AnalyzerEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("analyzer")
  private AnalyzerEnum analyzer = AnalyzerEnum.DEFAULT;

  @SerializedName("id")
  private String id = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("name_lower")
  private String nameLower = null;

  @SerializedName("alias")
  private String alias = null;

  @SerializedName("exclude")
  private Boolean exclude = null;

  @SerializedName("custom")
  private Boolean custom = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("composite")
  private Boolean composite = null;

  @SerializedName("suppressResistance")
  private Boolean suppressResistance = null;

  @SerializedName("approved")
  private Boolean approved = null;

  @SerializedName("availability")
  private List<DrugAvailability> availability = null;

  @SerializedName("synonyms")
  private List<DrugSynonyms> synonyms = null;

  @SerializedName("parents")
  private List<DrugParents> parents = null;

  @SerializedName("drugclass")
  private List<DrugDrugclass> drugclass = null;

  @SerializedName("compositeTags")
  private List<DrugCompositeTags> compositeTags = null;

  @SerializedName("brands")
  private List<DrugBrands> brands = null;

  @SerializedName("indicationText")
  private String indicationText = null;

  @SerializedName("contraindicationText")
  private String contraindicationText = null;

  @SerializedName("mechanismText")
  private String mechanismText = null;

  @SerializedName("rxcui")
  private List<String> rxcui = null;

  @SerializedName("externalIds")
  private List<DrugExternalIds> externalIds = null;

  @SerializedName("link")
  private String link = null;

  @SerializedName("prices")
  private List<DrugPrices> prices = null;

  @SerializedName("dosages")
  private List<DrugDosages> dosages = null;

  @SerializedName("pharmacology")
  private DrugPharmacology pharmacology = null;

  @SerializedName("phaseAndTrialsScore")
  private Float phaseAndTrialsScore = null;

  @SerializedName("_valid")
  private Object _valid = null;

  @SerializedName("_validMessage")
  private String _validMessage = null;

  public Drug mboost(Float mboost) {
    this.mboost = mboost;
    return this;
  }

   /**
   * Get mboost
   * @return mboost
  **/
  @Schema(description = "")
  public Float getMboost() {
    return mboost;
  }

  public void setMboost(Float mboost) {
    this.mboost = mboost;
  }

  public Drug analyzer(AnalyzerEnum analyzer) {
    this.analyzer = analyzer;
    return this;
  }

   /**
   * Get analyzer
   * @return analyzer
  **/
  @Schema(description = "")
  public AnalyzerEnum getAnalyzer() {
    return analyzer;
  }

  public void setAnalyzer(AnalyzerEnum analyzer) {
    this.analyzer = analyzer;
  }

  public Drug id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Drug source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(required = true, description = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public Drug name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Drug nameLower(String nameLower) {
    this.nameLower = nameLower;
    return this;
  }

   /**
   * Get nameLower
   * @return nameLower
  **/
  @Schema(required = true, description = "")
  public String getNameLower() {
    return nameLower;
  }

  public void setNameLower(String nameLower) {
    this.nameLower = nameLower;
  }

  public Drug alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @Schema(description = "")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public Drug exclude(Boolean exclude) {
    this.exclude = exclude;
    return this;
  }

   /**
   * Get exclude
   * @return exclude
  **/
  @Schema(description = "")
  public Boolean isExclude() {
    return exclude;
  }

  public void setExclude(Boolean exclude) {
    this.exclude = exclude;
  }

  public Drug custom(Boolean custom) {
    this.custom = custom;
    return this;
  }

   /**
   * Get custom
   * @return custom
  **/
  @Schema(description = "")
  public Boolean isCustom() {
    return custom;
  }

  public void setCustom(Boolean custom) {
    this.custom = custom;
  }

  public Drug description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Drug composite(Boolean composite) {
    this.composite = composite;
    return this;
  }

   /**
   * Get composite
   * @return composite
  **/
  @Schema(description = "")
  public Boolean isComposite() {
    return composite;
  }

  public void setComposite(Boolean composite) {
    this.composite = composite;
  }

  public Drug suppressResistance(Boolean suppressResistance) {
    this.suppressResistance = suppressResistance;
    return this;
  }

   /**
   * Get suppressResistance
   * @return suppressResistance
  **/
  @Schema(description = "")
  public Boolean isSuppressResistance() {
    return suppressResistance;
  }

  public void setSuppressResistance(Boolean suppressResistance) {
    this.suppressResistance = suppressResistance;
  }

  public Drug approved(Boolean approved) {
    this.approved = approved;
    return this;
  }

   /**
   * Get approved
   * @return approved
  **/
  @Schema(required = true, description = "")
  public Boolean isApproved() {
    return approved;
  }

  public void setApproved(Boolean approved) {
    this.approved = approved;
  }

  public Drug availability(List<DrugAvailability> availability) {
    this.availability = availability;
    return this;
  }

  public Drug addAvailabilityItem(DrugAvailability availabilityItem) {
    if (this.availability == null) {
      this.availability = new ArrayList<DrugAvailability>();
    }
    this.availability.add(availabilityItem);
    return this;
  }

   /**
   * Get availability
   * @return availability
  **/
  @Schema(description = "")
  public List<DrugAvailability> getAvailability() {
    return availability;
  }

  public void setAvailability(List<DrugAvailability> availability) {
    this.availability = availability;
  }

  public Drug synonyms(List<DrugSynonyms> synonyms) {
    this.synonyms = synonyms;
    return this;
  }

  public Drug addSynonymsItem(DrugSynonyms synonymsItem) {
    if (this.synonyms == null) {
      this.synonyms = new ArrayList<DrugSynonyms>();
    }
    this.synonyms.add(synonymsItem);
    return this;
  }

   /**
   * Get synonyms
   * @return synonyms
  **/
  @Schema(description = "")
  public List<DrugSynonyms> getSynonyms() {
    return synonyms;
  }

  public void setSynonyms(List<DrugSynonyms> synonyms) {
    this.synonyms = synonyms;
  }

  public Drug parents(List<DrugParents> parents) {
    this.parents = parents;
    return this;
  }

  public Drug addParentsItem(DrugParents parentsItem) {
    if (this.parents == null) {
      this.parents = new ArrayList<DrugParents>();
    }
    this.parents.add(parentsItem);
    return this;
  }

   /**
   * Get parents
   * @return parents
  **/
  @Schema(description = "")
  public List<DrugParents> getParents() {
    return parents;
  }

  public void setParents(List<DrugParents> parents) {
    this.parents = parents;
  }

  public Drug drugclass(List<DrugDrugclass> drugclass) {
    this.drugclass = drugclass;
    return this;
  }

  public Drug addDrugclassItem(DrugDrugclass drugclassItem) {
    if (this.drugclass == null) {
      this.drugclass = new ArrayList<DrugDrugclass>();
    }
    this.drugclass.add(drugclassItem);
    return this;
  }

   /**
   * Get drugclass
   * @return drugclass
  **/
  @Schema(description = "")
  public List<DrugDrugclass> getDrugclass() {
    return drugclass;
  }

  public void setDrugclass(List<DrugDrugclass> drugclass) {
    this.drugclass = drugclass;
  }

  public Drug compositeTags(List<DrugCompositeTags> compositeTags) {
    this.compositeTags = compositeTags;
    return this;
  }

  public Drug addCompositeTagsItem(DrugCompositeTags compositeTagsItem) {
    if (this.compositeTags == null) {
      this.compositeTags = new ArrayList<DrugCompositeTags>();
    }
    this.compositeTags.add(compositeTagsItem);
    return this;
  }

   /**
   * Get compositeTags
   * @return compositeTags
  **/
  @Schema(description = "")
  public List<DrugCompositeTags> getCompositeTags() {
    return compositeTags;
  }

  public void setCompositeTags(List<DrugCompositeTags> compositeTags) {
    this.compositeTags = compositeTags;
  }

  public Drug brands(List<DrugBrands> brands) {
    this.brands = brands;
    return this;
  }

  public Drug addBrandsItem(DrugBrands brandsItem) {
    if (this.brands == null) {
      this.brands = new ArrayList<DrugBrands>();
    }
    this.brands.add(brandsItem);
    return this;
  }

   /**
   * Get brands
   * @return brands
  **/
  @Schema(description = "")
  public List<DrugBrands> getBrands() {
    return brands;
  }

  public void setBrands(List<DrugBrands> brands) {
    this.brands = brands;
  }

  public Drug indicationText(String indicationText) {
    this.indicationText = indicationText;
    return this;
  }

   /**
   * Get indicationText
   * @return indicationText
  **/
  @Schema(description = "")
  public String getIndicationText() {
    return indicationText;
  }

  public void setIndicationText(String indicationText) {
    this.indicationText = indicationText;
  }

  public Drug contraindicationText(String contraindicationText) {
    this.contraindicationText = contraindicationText;
    return this;
  }

   /**
   * Get contraindicationText
   * @return contraindicationText
  **/
  @Schema(description = "")
  public String getContraindicationText() {
    return contraindicationText;
  }

  public void setContraindicationText(String contraindicationText) {
    this.contraindicationText = contraindicationText;
  }

  public Drug mechanismText(String mechanismText) {
    this.mechanismText = mechanismText;
    return this;
  }

   /**
   * Get mechanismText
   * @return mechanismText
  **/
  @Schema(description = "")
  public String getMechanismText() {
    return mechanismText;
  }

  public void setMechanismText(String mechanismText) {
    this.mechanismText = mechanismText;
  }

  public Drug rxcui(List<String> rxcui) {
    this.rxcui = rxcui;
    return this;
  }

  public Drug addRxcuiItem(String rxcuiItem) {
    if (this.rxcui == null) {
      this.rxcui = new ArrayList<String>();
    }
    this.rxcui.add(rxcuiItem);
    return this;
  }

   /**
   * Get rxcui
   * @return rxcui
  **/
  @Schema(description = "")
  public List<String> getRxcui() {
    return rxcui;
  }

  public void setRxcui(List<String> rxcui) {
    this.rxcui = rxcui;
  }

  public Drug externalIds(List<DrugExternalIds> externalIds) {
    this.externalIds = externalIds;
    return this;
  }

  public Drug addExternalIdsItem(DrugExternalIds externalIdsItem) {
    if (this.externalIds == null) {
      this.externalIds = new ArrayList<DrugExternalIds>();
    }
    this.externalIds.add(externalIdsItem);
    return this;
  }

   /**
   * Get externalIds
   * @return externalIds
  **/
  @Schema(description = "")
  public List<DrugExternalIds> getExternalIds() {
    return externalIds;
  }

  public void setExternalIds(List<DrugExternalIds> externalIds) {
    this.externalIds = externalIds;
  }

  public Drug link(String link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @Schema(description = "")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }

  public Drug prices(List<DrugPrices> prices) {
    this.prices = prices;
    return this;
  }

  public Drug addPricesItem(DrugPrices pricesItem) {
    if (this.prices == null) {
      this.prices = new ArrayList<DrugPrices>();
    }
    this.prices.add(pricesItem);
    return this;
  }

   /**
   * Get prices
   * @return prices
  **/
  @Schema(description = "")
  public List<DrugPrices> getPrices() {
    return prices;
  }

  public void setPrices(List<DrugPrices> prices) {
    this.prices = prices;
  }

  public Drug dosages(List<DrugDosages> dosages) {
    this.dosages = dosages;
    return this;
  }

  public Drug addDosagesItem(DrugDosages dosagesItem) {
    if (this.dosages == null) {
      this.dosages = new ArrayList<DrugDosages>();
    }
    this.dosages.add(dosagesItem);
    return this;
  }

   /**
   * Get dosages
   * @return dosages
  **/
  @Schema(description = "")
  public List<DrugDosages> getDosages() {
    return dosages;
  }

  public void setDosages(List<DrugDosages> dosages) {
    this.dosages = dosages;
  }

  public Drug pharmacology(DrugPharmacology pharmacology) {
    this.pharmacology = pharmacology;
    return this;
  }

   /**
   * Get pharmacology
   * @return pharmacology
  **/
  @Schema(description = "")
  public DrugPharmacology getPharmacology() {
    return pharmacology;
  }

  public void setPharmacology(DrugPharmacology pharmacology) {
    this.pharmacology = pharmacology;
  }

  public Drug phaseAndTrialsScore(Float phaseAndTrialsScore) {
    this.phaseAndTrialsScore = phaseAndTrialsScore;
    return this;
  }

   /**
   * Get phaseAndTrialsScore
   * @return phaseAndTrialsScore
  **/
  @Schema(description = "")
  public Float getPhaseAndTrialsScore() {
    return phaseAndTrialsScore;
  }

  public void setPhaseAndTrialsScore(Float phaseAndTrialsScore) {
    this.phaseAndTrialsScore = phaseAndTrialsScore;
  }

  public Drug _valid(Object _valid) {
    this._valid = _valid;
    return this;
  }

   /**
   * Get _valid
   * @return _valid
  **/
  @Schema(description = "")
  public Object getValid() {
    return _valid;
  }

  public void setValid(Object _valid) {
    this._valid = _valid;
  }

  public Drug _validMessage(String _validMessage) {
    this._validMessage = _validMessage;
    return this;
  }

   /**
   * Get _validMessage
   * @return _validMessage
  **/
  @Schema(description = "")
  public String getValidMessage() {
    return _validMessage;
  }

  public void setValidMessage(String _validMessage) {
    this._validMessage = _validMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Drug drug = (Drug) o;
    return Objects.equals(this.mboost, drug.mboost) &&
        Objects.equals(this.analyzer, drug.analyzer) &&
        Objects.equals(this.id, drug.id) &&
        Objects.equals(this.source, drug.source) &&
        Objects.equals(this.name, drug.name) &&
        Objects.equals(this.nameLower, drug.nameLower) &&
        Objects.equals(this.alias, drug.alias) &&
        Objects.equals(this.exclude, drug.exclude) &&
        Objects.equals(this.custom, drug.custom) &&
        Objects.equals(this.description, drug.description) &&
        Objects.equals(this.composite, drug.composite) &&
        Objects.equals(this.suppressResistance, drug.suppressResistance) &&
        Objects.equals(this.approved, drug.approved) &&
        Objects.equals(this.availability, drug.availability) &&
        Objects.equals(this.synonyms, drug.synonyms) &&
        Objects.equals(this.parents, drug.parents) &&
        Objects.equals(this.drugclass, drug.drugclass) &&
        Objects.equals(this.compositeTags, drug.compositeTags) &&
        Objects.equals(this.brands, drug.brands) &&
        Objects.equals(this.indicationText, drug.indicationText) &&
        Objects.equals(this.contraindicationText, drug.contraindicationText) &&
        Objects.equals(this.mechanismText, drug.mechanismText) &&
        Objects.equals(this.rxcui, drug.rxcui) &&
        Objects.equals(this.externalIds, drug.externalIds) &&
        Objects.equals(this.link, drug.link) &&
        Objects.equals(this.prices, drug.prices) &&
        Objects.equals(this.dosages, drug.dosages) &&
        Objects.equals(this.pharmacology, drug.pharmacology) &&
        Objects.equals(this.phaseAndTrialsScore, drug.phaseAndTrialsScore) &&
        Objects.equals(this._valid, drug._valid) &&
        Objects.equals(this._validMessage, drug._validMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mboost, analyzer, id, source, name, nameLower, alias, exclude, custom, description, composite, suppressResistance, approved, availability, synonyms, parents, drugclass, compositeTags, brands, indicationText, contraindicationText, mechanismText, rxcui, externalIds, link, prices, dosages, pharmacology, phaseAndTrialsScore, _valid, _validMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Drug {\n");
    
    sb.append("    mboost: ").append(toIndentedString(mboost)).append("\n");
    sb.append("    analyzer: ").append(toIndentedString(analyzer)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameLower: ").append(toIndentedString(nameLower)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    exclude: ").append(toIndentedString(exclude)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    composite: ").append(toIndentedString(composite)).append("\n");
    sb.append("    suppressResistance: ").append(toIndentedString(suppressResistance)).append("\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    synonyms: ").append(toIndentedString(synonyms)).append("\n");
    sb.append("    parents: ").append(toIndentedString(parents)).append("\n");
    sb.append("    drugclass: ").append(toIndentedString(drugclass)).append("\n");
    sb.append("    compositeTags: ").append(toIndentedString(compositeTags)).append("\n");
    sb.append("    brands: ").append(toIndentedString(brands)).append("\n");
    sb.append("    indicationText: ").append(toIndentedString(indicationText)).append("\n");
    sb.append("    contraindicationText: ").append(toIndentedString(contraindicationText)).append("\n");
    sb.append("    mechanismText: ").append(toIndentedString(mechanismText)).append("\n");
    sb.append("    rxcui: ").append(toIndentedString(rxcui)).append("\n");
    sb.append("    externalIds: ").append(toIndentedString(externalIds)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("    dosages: ").append(toIndentedString(dosages)).append("\n");
    sb.append("    pharmacology: ").append(toIndentedString(pharmacology)).append("\n");
    sb.append("    phaseAndTrialsScore: ").append(toIndentedString(phaseAndTrialsScore)).append("\n");
    sb.append("    _valid: ").append(toIndentedString(_valid)).append("\n");
    sb.append("    _validMessage: ").append(toIndentedString(_validMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
