/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MongoTrialSynonyms
 */


public class MongoTrialSynonyms {
  @SerializedName("suppress")
  private Boolean suppress = null;

  @SerializedName("custom")
  private Boolean custom = null;

  @SerializedName("ctlink")
  private Boolean ctlink = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Gets or Sets analyzer
   */
  @JsonAdapter(AnalyzerEnum.Adapter.class)
  public enum AnalyzerEnum {
    DEFAULT("DEFAULT"),
    CASE_SENSITIVE("CASE_SENSITIVE");

    private String value;

    AnalyzerEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AnalyzerEnum fromValue(String text) {
      for (AnalyzerEnum b : AnalyzerEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AnalyzerEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalyzerEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalyzerEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AnalyzerEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("analyzer")
  private AnalyzerEnum analyzer = AnalyzerEnum.DEFAULT;

  public MongoTrialSynonyms suppress(Boolean suppress) {
    this.suppress = suppress;
    return this;
  }

   /**
   * Get suppress
   * @return suppress
  **/
  @Schema(description = "")
  public Boolean isSuppress() {
    return suppress;
  }

  public void setSuppress(Boolean suppress) {
    this.suppress = suppress;
  }

  public MongoTrialSynonyms custom(Boolean custom) {
    this.custom = custom;
    return this;
  }

   /**
   * Get custom
   * @return custom
  **/
  @Schema(description = "")
  public Boolean isCustom() {
    return custom;
  }

  public void setCustom(Boolean custom) {
    this.custom = custom;
  }

  public MongoTrialSynonyms ctlink(Boolean ctlink) {
    this.ctlink = ctlink;
    return this;
  }

   /**
   * Get ctlink
   * @return ctlink
  **/
  @Schema(description = "")
  public Boolean isCtlink() {
    return ctlink;
  }

  public void setCtlink(Boolean ctlink) {
    this.ctlink = ctlink;
  }

  public MongoTrialSynonyms name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MongoTrialSynonyms analyzer(AnalyzerEnum analyzer) {
    this.analyzer = analyzer;
    return this;
  }

   /**
   * Get analyzer
   * @return analyzer
  **/
  @Schema(description = "")
  public AnalyzerEnum getAnalyzer() {
    return analyzer;
  }

  public void setAnalyzer(AnalyzerEnum analyzer) {
    this.analyzer = analyzer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MongoTrialSynonyms mongoTrialSynonyms = (MongoTrialSynonyms) o;
    return Objects.equals(this.suppress, mongoTrialSynonyms.suppress) &&
        Objects.equals(this.custom, mongoTrialSynonyms.custom) &&
        Objects.equals(this.ctlink, mongoTrialSynonyms.ctlink) &&
        Objects.equals(this.name, mongoTrialSynonyms.name) &&
        Objects.equals(this.analyzer, mongoTrialSynonyms.analyzer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suppress, custom, ctlink, name, analyzer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MongoTrialSynonyms {\n");
    
    sb.append("    suppress: ").append(toIndentedString(suppress)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    ctlink: ").append(toIndentedString(ctlink)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    analyzer: ").append(toIndentedString(analyzer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
