/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Require more than one filter match for a particular facet.  For instance setting MUTATION to 2 would mean that a record would have to match 2 of the MUTATION filters provided.
 */
@Schema(description = "Require more than one filter match for a particular facet.  For instance setting MUTATION to 2 would mean that a record would have to match 2 of the MUTATION filters provided.")

public class SearchRequestMinShouldMatch {
  @SerializedName("MUTATION")
  private Integer MUTATION = null;

  @SerializedName("GENE")
  private Integer GENE = null;

  public SearchRequestMinShouldMatch MUTATION(Integer MUTATION) {
    this.MUTATION = MUTATION;
    return this;
  }

   /**
   * Get MUTATION
   * @return MUTATION
  **/
  @Schema(description = "")
  public Integer getMUTATION() {
    return MUTATION;
  }

  public void setMUTATION(Integer MUTATION) {
    this.MUTATION = MUTATION;
  }

  public SearchRequestMinShouldMatch GENE(Integer GENE) {
    this.GENE = GENE;
    return this;
  }

   /**
   * Get GENE
   * @return GENE
  **/
  @Schema(description = "")
  public Integer getGENE() {
    return GENE;
  }

  public void setGENE(Integer GENE) {
    this.GENE = GENE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRequestMinShouldMatch searchRequestMinShouldMatch = (SearchRequestMinShouldMatch) o;
    return Objects.equals(this.MUTATION, searchRequestMinShouldMatch.MUTATION) &&
        Objects.equals(this.GENE, searchRequestMinShouldMatch.GENE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(MUTATION, GENE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRequestMinShouldMatch {\n");
    
    sb.append("    MUTATION: ").append(toIndentedString(MUTATION)).append("\n");
    sb.append("    GENE: ").append(toIndentedString(GENE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
