/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Assertion;
import io.swagger.client.model.SearchRequest;
import io.swagger.client.model.SearchResponseDrug;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for AssertionsApi
 */
@Ignore
public class AssertionsApiTest {

    private final AssertionsApi api = new AssertionsApi();

    /**
     * Get an Assertion
     *
     * Get an evidence backed assertion
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAssertionTest() throws ApiException {
        String id = null;
        Assertion response = api.getAssertion(id);

        // TODO: test validations
    }
    /**
     * Search for assertions
     *
     * Search for evidence backed assertions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchAssertionsTest() throws ApiException {
        SearchRequest body = null;
        SearchResponseDrug response = api.searchAssertions(body);

        // TODO: test validations
    }
}
