/*
 * MolecularMatch MMPower
 * MMPower API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@molecularmatch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ClinicalTrial;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for ClinicalTrialApi
 */
@Ignore
public class ClinicalTrialApiTest {

    private final ClinicalTrialApi api = new ClinicalTrialApi();

    /**
     * Get a Clinical Trial
     *
     * Get a Clinical Trial
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTrialTest() throws ApiException {
        String :Id = null;
        ClinicalTrial response = api.getTrial(:Id);

        // TODO: test validations
    }
}
